"""add users table, modify email indexes, add attachment fields, LONGTEXT

Revision ID: c6d951c16aa8
Revises: f396171c47b5
Create Date: 2026-06-08 11:16:15.167152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6d951c16aa8'
down_revision: Union[str, Sequence[str], None] = 'f396171c47b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('attachments', sa.Column('storage_backend', sa.String(length=50), nullable=True))
    op.add_column('attachments', sa.Column('content_sha256', sa.String(length=64), nullable=True))
    op.add_column('attachments', sa.Column('is_inline', sa.Boolean(), nullable=False))
    op.add_column('attachments', sa.Column('content_id', sa.String(length=255), nullable=True))
    op.alter_column('email_messages', 'body_text',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('email_messages', 'body_html',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('message_id'), table_name='email_messages')
    op.drop_index(op.f('raw_sha256'), table_name='email_messages')
    op.create_index('ix_email_messages_mailbox_message_id', 'email_messages', ['mailbox_id', 'message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_raw_sha256'), 'email_messages', ['raw_sha256'], unique=False)
    op.create_unique_constraint('uq_mailbox_raw_sha256', 'email_messages', ['mailbox_id', 'raw_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mailbox_raw_sha256', 'email_messages', type_='unique')
    op.drop_index(op.f('ix_email_messages_raw_sha256'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_index('ix_email_messages_mailbox_message_id', table_name='email_messages')
    op.create_index(op.f('raw_sha256'), 'email_messages', ['raw_sha256'], unique=True)
    op.create_index(op.f('message_id'), 'email_messages', ['message_id'], unique=True)
    op.alter_column('email_messages', 'body_html',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('email_messages', 'body_text',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('attachments', 'content_id')
    op.drop_column('attachments', 'is_inline')
    op.drop_column('attachments', 'content_sha256')
    op.drop_column('attachments', 'storage_backend')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
